# Learning Numpy

In [4]:
import numpy as np

In [5]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [11]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [12]:
type(list1)


list

In [13]:
type(arr1)

numpy.ndarray

In [15]:
arr2 = np.arange(10, 21, 2)
arr2


array([10, 12, 14, 16, 18, 20])

In [16]:
list2 = [40, 50, 60]
list2 

[40, 50, 60]

In [17]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [19]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
arr3.shape

(2, 3)

In [21]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [2, 3, 4]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 4]]])

In [22]:
arr4.shape

(2, 2, 3)

In [23]:
arr1 * 3

array([30, 60, 90])

In [24]:
arr4 * 3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [ 6,  9, 12]]])

In [25]:
arr2 = np.array(list2)
arr2

array([40, 50, 60])

In [26]:
arr1 * arr2

array([ 400, 1000, 1800])

In [27]:
arr1 * arr4

array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 70, 160, 270],
        [ 20,  60, 120]]])

In [28]:
arr1

array([10, 20, 30])

In [32]:
arr1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr1D.shape

(12,)

In [31]:
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2D.shape

(3, 4)

In [33]:
arr3D = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]],[[21,22,23,24],[25,26,27,28],[29,30,31,32],[33,34,35,36],[37,38,39,40]]])
arr3D.shape

(2, 5, 4)

In [34]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [40]:
arr3[1]

array([40, 50, 60])

In [41]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [48]:
arr3.min()

10

In [57]:
for x in (arr3D):
    print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]
